import { useState, useCallback, useEffect, useRef } from 'react';

// 적 정보 (임시로 하드코딩, 나중에 데이터 파일로 분리 가능)
const BOSS_DATA = {
  name: '화염룡',
    maxHp: 5000,
      atk: 150,
        element: 'FIRE',
          img: 'BOSS'
          };

          export const useBattleSystem = (party) => {
            const [battleState, setBattleState] = useState('IDLE'); // IDLE, FIGHTING, VICTORY, DEFEAT
              const [logs, setLogs] = useState([]);
                const [enemy, setEnemy] = useState(null);
                  const [allies, setAllies] = useState([]);
                    const [turnCount, setTurnCount] = useState(0);

                      // 전투 루프를 위한 Interval Ref
                        const battleInterval = useRef(null);

                          // 로그 추가 함수
                            const addLog = useCallback((msg) => {
                                setLogs(prev => [...prev.slice(-4), msg]); // 최근 5개만 유지
                                  }, []);

                                    // 전투 시작 초기화
                                      const startBattle = useCallback(() => {
                                          // 파티원 데이터를 전투용 객체로 변환 (현재 체력 hp 추가)
                                              const battleAllies = [...party.front, ...party.back]
                                                    .filter(c => c !== null)
                                                          .map(c => ({
                                                                  ...c,
                                                                          maxHp: c.baseHp, // 실제론 레벨/장비 보정 필요
                                                                                  hp: c.baseHp,
                                                                                          atk: c.baseAtk,
                                                                                                  isDead: false
                                                                                                        }));

                                                                                                            if (battleAllies.length === 0) {
                                                                                                                  addLog("출전할 캐릭터가 없습니다!");
                                                                                                                        return;
                                                                                                                            }

                                                                                                                                setAllies(battleAllies);
                                                                                                                                    setEnemy({ ...BOSS_DATA, hp: BOSS_DATA.maxHp });
                                                                                                                                        setBattleState('FIGHTING');
                                                                                                                                            setLogs(['> 전투가 시작되었습니다!', `> BOSS [${BOSS_DATA.name}] 등장!`]);
                                                                                                                                                setTurnCount(0);
                                                                                                                                                  }, [party, addLog]);

                                                                                                                                                    // 턴 진행 로직 (1초마다 실행)
                                                                                                                                                      const processTurn = useCallback(() => {
                                                                                                                                                          if (battleState !== 'FIGHTING') return;

                                                                                                                                                              setTurnCount(prev => prev + 1);
                                                                                                                                                                  let currentEnemy = { ...enemy };
                                                                                                                                                                      let currentAllies = [...allies];
                                                                                                                                                                          let turnLogs = [];

                                                                                                                                                                              // 1. 아군 턴: 살아있는 아군들이 보스를 공격
                                                                                                                                                                                  currentAllies.forEach(ally => {
                                                                                                                                                                                        if (ally.isDead) return;

                                                                                                                                                                                              // 공격 (임시 데미지 공식: 공격력 ±10%)
                                                                                                                                                                                                    const dmg = Math.floor(ally.atk * (0.9 + Math.random() * 0.2));
                                                                                                                                                                                                          currentEnemy.hp = Math.max(0, currentEnemy.hp - dmg);
                                                                                                                                                                                                                turnLogs.push(`> [${ally.name}]의 공격! ${dmg} 피해.`);

                                                                                                                                                                                                                      // 보스 사망 체크
                                                                                                                                                                                                                            if (currentEnemy.hp <= 0) {
                                                                                                                                                                                                                                    setBattleState('VICTORY');
                                                                                                                                                                                                                                            turnLogs.push(`> [${currentEnemy.name}] 처치! 승리했습니다!`);
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                          // 2. 적군 턴: 보스가 살아있다면 랜덤 아군 공격
                                                                                                                                                                                                                                                              if (currentEnemy.hp > 0) {
                                                                                                                                                                                                                                                                    const livingAllies = currentAllies.filter(a => !a.isDead);
                                                                                                                                                                                                                                                                          if (livingAllies.length > 0) {
                                                                                                                                                                                                                                                                                  const targetIdx = Math.floor(Math.random() * livingAllies.length);
                                                                                                                                                                                                                                                                                          const target = livingAllies[targetIdx];
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                          // 보스 공격 (속성 상성 등은 나중에 추가)
                                                                                                                                                                                                                                                                                                                  const dmg = Math.floor(currentEnemy.atk * (0.8 + Math.random() * 0.4));
                                                                                                                                                                                                                                                                                                                          target.hp = Math.max(0, target.hp - dmg);
                                                                                                                                                                                                                                                                                                                                  turnLogs.push(`> [${currentEnemy.name}]의 공격! [${target.name}]에게 ${dmg} 피해.`);

                                                                                                                                                                                                                                                                                                                                          if (target.hp <= 0) {
                                                                                                                                                                                                                                                                                                                                                    target.isDead = true;
                                                                                                                                                                                                                                                                                                                                                              turnLogs.push(`> [${target.name}] 전투 불능...`);
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                    // 아군 전멸
                                                                                                                                                                                                                                                                                                                                                                                            setBattleState('DEFEAT');
                                                                                                                                                                                                                                                                                                                                                                                                    turnLogs.push(`> 아군이 전멸했습니다. 패배...`);
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                  // 상태 업데이트
                                                                                                                                                                                                                                                                                                                                                                                                                      setEnemy(currentEnemy);
                                                                                                                                                                                                                                                                                                                                                                                                                          setAllies(currentAllies);
                                                                                                                                                                                                                                                                                                                                                                                                                              turnLogs.forEach(log => addLog(log));

                                                                                                                                                                                                                                                                                                                                                                                                                                }, [battleState, enemy, allies, addLog]);

                                                                                                                                                                                                                                                                                                                                                                                                                                  // 전투 타이머 관리
                                                                                                                                                                                                                                                                                                                                                                                                                                    useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (battleState === 'FIGHTING') {
                                                                                                                                                                                                                                                                                                                                                                                                                                              battleInterval.current = setInterval(processTurn, 1000); // 1초마다 턴 진행
                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (battleInterval.current) clearInterval(battleInterval.current);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (battleInterval.current) clearInterval(battleInterval.current);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, [battleState, processTurn]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  battleState, // 상태
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      logs,        // 전투 로그
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          enemy,       // 적 정보 (체력 포함)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              allies,      // 아군 정보 (체력 포함)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  startBattle, // 전투 시작 함수
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      turnCount    // 턴 수
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        