/**
 * 속성 반응 시스템
 * 두 속성이 만났을 때 발생하는 현상(Phenomenon)을 정의
 */

// 현상(Phenomenon) 정의
export const PHENOMENA = {
  FUSION: 'FUSION',                // 핵융합: ENTROPY + GRAVITY
  THERMAL_SHOCK: 'THERMAL_SHOCK',  // 열충격: ENTROPY + STASIS
  PLASMA: 'PLASMA',                // 플라즈마: ENTROPY + RESONANCE
  ABSOLUTE_ZERO: 'ABSOLUTE_ZERO',  // 절대영도: STASIS + GRAVITY
  OVERLOAD: 'OVERLOAD',            // 과부하: STASIS + RESONANCE
  BLACK_HOLE: 'BLACK_HOLE',        // 블랙홀: GRAVITY + RESONANCE
};

// 특수 반응 결과
export const SPECIAL_REACTIONS = {
  PARADOX_TRIGGER: 'PARADOX_TRIGGER',  // 패러독스 발동 (+100점)
  AXIOM_TRIGGER: 'AXIOM_TRIGGER',      // 공리 안정화 (+30점)
};

/**
 * 속성 조합 → 현상 매핑 테이블
 * 두 속성의 순서는 무관하게 동일한 결과를 반환
 * 예: (ENTROPY, GRAVITY) === (GRAVITY, ENTROPY)
 */
export const REACTION_TABLE = {
  // ENTROPY 조합
  'ENTROPY,GRAVITY': PHENOMENA.FUSION,
  'GRAVITY,ENTROPY': PHENOMENA.FUSION,
  
  'ENTROPY,STASIS': PHENOMENA.THERMAL_SHOCK,
  'STASIS,ENTROPY': PHENOMENA.THERMAL_SHOCK,
  
  'ENTROPY,RESONANCE': PHENOMENA.PLASMA,
  'RESONANCE,ENTROPY': PHENOMENA.PLASMA,
  
  // STASIS 조합
  'STASIS,GRAVITY': PHENOMENA.ABSOLUTE_ZERO,
  'GRAVITY,STASIS': PHENOMENA.ABSOLUTE_ZERO,
  
  'STASIS,RESONANCE': PHENOMENA.OVERLOAD,
  'RESONANCE,STASIS': PHENOMENA.OVERLOAD,
  
  // GRAVITY-RESONANCE 조합
  'GRAVITY,RESONANCE': PHENOMENA.BLACK_HOLE,
  'RESONANCE,GRAVITY': PHENOMENA.BLACK_HOLE,
};

/**
 * CHAOS 미션에 유리한 현상들
 */
export const CHAOS_PHENOMENA = [
  PHENOMENA.FUSION,
  PHENOMENA.THERMAL_SHOCK,
  PHENOMENA.PLASMA,
];

/**
 * SILENCE 미션에 유리한 현상들
 */
export const SILENCE_PHENOMENA = [
  PHENOMENA.ABSOLUTE_ZERO,
  PHENOMENA.OVERLOAD,
  PHENOMENA.BLACK_HOLE,
];
